title: Teruo's Journal
author:
  name: Teruo
  email: hi@teruo.dev
description: >
  Learnings on software, productivity, and Japanese —
  exploring code, habits, and ideas for a smarter workflow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://teruo.dev" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: auto

  nav_pages:
    - about.md

